import React, { useEffect, useState } from 'react';
import { Calendar, CheckCircle, ChevronDown, Clock, Edit2, ExternalLink, Filter, Plus, RotateCcw, Search, Trash2, Trophy, X } from 'lucide-react';
import { CalendarItem, Hackathon } from '../types';
import { CALENDAR_STORAGE_KEY, formatDateInput, getCalendarMaxDate, isCalendarDateAllowed, sanitizeCalendarItems, sortCalendarItems, sortHackathonsByDeadline } from '../utils/calendarUtils';

type Priority = NonNullable<Hackathon['priority']>;
type ContentFilter = 'all' | 'hackathons' | 'tasks';
type TypeFilter = 'all' | 'in-person' | 'virtual';

const priorities: { value: Priority; label: string; picker: string; card: string; muted: string; panel: string }[] = [
  { value: 'rose', label: 'Highly Imp', picker: 'bg-rose-600 text-white', card: 'border-rose-400 bg-rose-600 text-white', muted: 'text-white/75', panel: 'bg-white/15 border-white/20' },
  { value: 'amber', label: 'Priority', picker: 'bg-amber-300 text-slate-950', card: 'border-amber-200 bg-amber-300 text-slate-950', muted: 'text-slate-950/70', panel: 'bg-black/10 border-black/10' },
  { value: 'emerald', label: 'Low Priority', picker: 'bg-emerald-400 text-slate-950', card: 'border-emerald-300 bg-emerald-400 text-slate-950', muted: 'text-slate-950/70', panel: 'bg-black/10 border-black/10' },
  { value: 'blue', label: 'Casual', picker: 'bg-sky-300 text-slate-950', card: 'border-sky-200 bg-sky-300 text-slate-950', muted: 'text-slate-950/70', panel: 'bg-black/10 border-black/10' },
  { value: 'slate', label: 'Not Set', picker: 'bg-slate-600 text-white', card: 'border-slate-800 bg-slate-900 text-white', muted: 'text-slate-400', panel: 'bg-slate-800 border-slate-700' },
];
const priorityFor = (value?: Priority) => priorities.find((priority) => priority.value === (value || 'slate')) || priorities[4];
const emptyHackathon: Omit<Hackathon, 'id'> = { name: '', deadline: '', link: '', platform: '', type: 'virtual', priority: 'slate' };

const HackathonTracker: React.FC = () => {
  const [hackathons, setHackathons] = useState<Hackathon[]>([]);
  const [tasks, setTasks] = useState<CalendarItem[]>([]);
  const [hasLoadedHackathons, setHasLoadedHackathons] = useState(false);
  const [isAdding, setIsAdding] = useState(false);
  const [isAddingTask, setIsAddingTask] = useState(false);
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [contentFilter, setContentFilter] = useState<ContentFilter>('all');
  const [typeFilter, setTypeFilter] = useState<TypeFilter>('all');
  const [priorityFilter, setPriorityFilter] = useState<'all' | Priority>('all');
  const [colourOpen, setColourOpen] = useState(false);
  const [search, setSearch] = useState('');
  const [linkType, setLinkType] = useState<'submit' | 'in-person'>('submit');
  const [newItem, setNewItem] = useState(emptyHackathon);
  const [task, setTask] = useState<{ title: string; date: string; time: string; color: CalendarItem['color'] }>({ title: '', date: formatDateInput(new Date()), time: '', color: 'amber' });

  useEffect(() => {
    try { const saved = localStorage.getItem('solomon_hackathons'); setHackathons(saved ? sortHackathonsByDeadline(JSON.parse(saved)) : []); } catch { setHackathons([]); }
    setHasLoadedHackathons(true);
  }, []);
  useEffect(() => { if (hasLoadedHackathons) localStorage.setItem('solomon_hackathons', JSON.stringify(hackathons)); }, [hackathons, hasLoadedHackathons]);
  useEffect(() => {
    const loadTasks = () => { try { const saved = localStorage.getItem(CALENDAR_STORAGE_KEY); setTasks(saved ? sanitizeCalendarItems(JSON.parse(saved)) : []); } catch { setTasks([]); } };
    loadTasks(); window.addEventListener('solomon-calendar-updated', loadTasks); window.addEventListener('storage', loadTasks);
    return () => { window.removeEventListener('solomon-calendar-updated', loadTasks); window.removeEventListener('storage', loadTasks); };
  }, []);

  const closeHackathon = () => { setIsAdding(false); setEditingId(null); setLinkType('submit'); setNewItem(emptyHackathon); };
  const saveHackathon = () => {
    if (!newItem.name.trim() || !newItem.deadline) return;
    const item = { ...newItem, name: newItem.name.trim(), link: linkType === 'in-person' ? '' : newItem.link };
    setHackathons((current) => sortHackathonsByDeadline(editingId ? current.map((hackathon) => hackathon.id === editingId ? { ...item, id: editingId } : hackathon) : [...current, { ...item, id: Date.now().toString() }]));
    closeHackathon();
  };
  const editHackathon = (hackathon: Hackathon) => { setNewItem({ name: hackathon.name, deadline: hackathon.deadline, link: hackathon.link, platform: hackathon.platform, type: hackathon.type, priority: hackathon.priority || 'slate' }); setLinkType(hackathon.link ? 'submit' : 'in-person'); setEditingId(hackathon.id); setIsAdding(true); };
  const saveTask = () => {
    if (!task.title.trim() || !isCalendarDateAllowed(task.date)) return;
    const updatedTask = { title: task.title.trim(), date: task.date, time: task.time || undefined, color: task.color, source: 'manual' as const };
    const next = sortCalendarItems(editingTaskId ? tasks.map((item) => item.id === editingTaskId ? { ...item, ...updatedTask } : item) : [...tasks, { id: `task-${Date.now()}`, ...updatedTask, completed: false }]);
    localStorage.setItem(CALENDAR_STORAGE_KEY, JSON.stringify(next)); setTasks(next); window.dispatchEvent(new Event('solomon-calendar-updated'));
    setTask({ title: '', date: formatDateInput(new Date()), time: '', color: 'amber' }); setEditingTaskId(null); setIsAddingTask(false);
  };
  const editTask = (item: CalendarItem) => { setTask({ title: item.title, date: item.date, time: item.time || '', color: item.color }); setEditingTaskId(item.id); setIsAddingTask(true); };
  const deleteTask = (id: string) => { const next = tasks.filter((item) => item.id !== id); localStorage.setItem(CALENDAR_STORAGE_KEY, JSON.stringify(next)); setTasks(next); window.dispatchEvent(new Event('solomon-calendar-updated')); };
  const moveTaskToToday = (id: string) => { const next = sortCalendarItems(tasks.map((item) => item.id === id ? { ...item, date: formatDateInput(new Date()), completed: false } : item)); localStorage.setItem(CALENDAR_STORAGE_KEY, JSON.stringify(next)); setTasks(next); window.dispatchEvent(new Event('solomon-calendar-updated')); };
  const matches = (name: string, color: Priority) => name.toLowerCase().includes(search.toLowerCase()) && (priorityFilter === 'all' || color === priorityFilter);
  const visibleHackathons = hackathons.filter((hackathon) => (typeFilter === 'all' || hackathon.type === typeFilter) && matches(hackathon.name, hackathon.priority || 'slate'));
  const visibleTasks = tasks.filter((item) => matches(item.title, item.color));
  const daysLeft = (date: string) => Math.ceil((new Date(date).getTime() - Date.now()) / 86400000);
  const selectedColour = priorityFilter === 'all' ? 'All colours' : priorityFor(priorityFilter).label;
  const allByDate = [...new Set([...visibleHackathons.map((item) => item.deadline), ...visibleTasks.map((item) => item.date)])].sort().map((date) => ({ date, hackathons: visibleHackathons.filter((item) => item.deadline === date), tasks: sortCalendarItems(visibleTasks.filter((item) => item.date === date)) }));

  return <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-2xl font-bold text-white"><Trophy className="h-6 w-6 text-amber-500" />Hackathon Deadlines</h2><div className="flex gap-2"><button onClick={() => setIsAddingTask(true)} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold text-white hover:bg-indigo-500"><Plus className="h-4 w-4" />Add Task</button><button onClick={() => setIsAdding(true)} className="flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2 text-sm font-bold text-white hover:bg-amber-500"><Plus className="h-4 w-4" />Track Hackathon</button></div></div>
    <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><div className="flex items-center gap-2 text-sm text-slate-400"><Filter className="h-4 w-4" /><span className="font-bold">Show:</span></div>{([{ value: 'all', label: 'All' }, { value: 'hackathons', label: 'Hackathons' }, { value: 'tasks', label: 'Tasks' }] as const).map((option) => <button key={option.value} onClick={() => setContentFilter(option.value)} className={`rounded-lg px-4 py-2 text-sm font-bold ${contentFilter === option.value ? 'bg-amber-600 text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'}`}>{option.label}</button>)}<span className="ml-1 text-xs font-bold uppercase tracking-widest text-slate-500">Hackathon type</span>{(['all', 'in-person', 'virtual'] as TypeFilter[]).map((value) => <button key={value} onClick={() => setTypeFilter(value)} className={`rounded-lg px-3 py-2 text-sm font-bold ${typeFilter === value ? 'bg-slate-200 text-slate-950' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'}`}>{value === 'all' ? 'All' : value === 'in-person' ? 'In Person' : 'Virtual'}</button>)}<div className="relative"><button onClick={() => setColourOpen((open) => !open)} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-bold ${priorityFilter === 'all' ? 'bg-slate-800 text-slate-300' : priorityFor(priorityFilter).picker}`}><span>{selectedColour}</span><ChevronDown className={`h-4 w-4 transition-transform ${colourOpen ? 'rotate-180' : ''}`} /></button>{colourOpen && <div className="absolute right-0 z-20 mt-2 w-44 rounded-xl border border-slate-700 bg-slate-900 p-2 shadow-2xl">{([{ value: 'all', label: 'All colours' }, ...priorities] as const).map((option) => <button key={option.value} onClick={() => { setPriorityFilter(option.value); setColourOpen(false); }} className={`mb-1 block w-full rounded-lg px-3 py-2 text-left text-sm font-bold last:mb-0 ${option.value === 'all' ? 'bg-slate-800 text-white hover:bg-slate-700' : option.picker}`}>{option.label}</button>)}</div>}</div></div><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks and hackathons..." className="w-full rounded-lg border border-slate-700 bg-slate-800 py-2 pl-10 pr-10 text-white outline-none focus:ring-2 focus:ring-amber-500" />{search && <button onClick={() => setSearch('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500"><X className="h-4 w-4" /></button>}</div></div>
    {contentFilter === 'all' ? <div className="space-y-10">{allByDate.map(({ date, hackathons: datedHackathons, tasks: datedTasks }) => <section key={date}><div className="mb-4 flex items-center gap-3"><span className="h-px flex-1 bg-slate-800" /><h3 className="rounded-full border border-indigo-500/30 bg-indigo-500/10 px-4 py-2 text-sm font-black text-indigo-200">{new Date(`${date}T00:00:00`).toLocaleDateString('en-IN', { dateStyle: 'full' })}</h3><span className="h-px flex-1 bg-slate-800" /></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{datedHackathons.map((hackathon) => <HackathonCard key={hackathon.id} hackathon={hackathon} onEdit={() => editHackathon(hackathon)} onDelete={() => setHackathons((current) => current.filter((item) => item.id !== hackathon.id))} daysLeft={daysLeft(hackathon.deadline)} />)}{datedTasks.map((item) => <TaskCard key={item.id} item={item} onEdit={() => editTask(item)} onDelete={() => deleteTask(item.id)} onMoveToToday={() => moveTaskToToday(item.id)} />)}</div></section>)}{!allByDate.length && <EmptyState filter="all" />}</div> : <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{contentFilter === 'hackathons' && visibleHackathons.map((hackathon) => <HackathonCard key={hackathon.id} hackathon={hackathon} onEdit={() => editHackathon(hackathon)} onDelete={() => setHackathons((current) => current.filter((item) => item.id !== hackathon.id))} daysLeft={daysLeft(hackathon.deadline)} />)}{contentFilter === 'tasks' && visibleTasks.map((item) => <TaskCard key={item.id} item={item} onEdit={() => editTask(item)} onDelete={() => deleteTask(item.id)} onMoveToToday={() => moveTaskToToday(item.id)} />)}{((contentFilter === 'hackathons' && !visibleHackathons.length) || (contentFilter === 'tasks' && !visibleTasks.length)) && <EmptyState filter={contentFilter} />}</div>}
    {(isAdding || isAddingTask) && <Modal>{isAdding ? <HackathonForm item={newItem} setItem={setNewItem} linkType={linkType} setLinkType={setLinkType} editing={Boolean(editingId)} onCancel={closeHackathon} onSave={saveHackathon} /> : <TaskForm task={task} setTask={setTask} editing={Boolean(editingTaskId)} onCancel={() => { setIsAddingTask(false); setEditingTaskId(null); }} onSave={saveTask} />}</Modal>}
  </div>;
};

const HackathonCard: React.FC<{ hackathon: Hackathon; daysLeft: number; onEdit: () => void; onDelete: () => void }> = ({ hackathon, daysLeft, onEdit, onDelete }) => { const priority = priorityFor(hackathon.priority); return <div className={`group relative overflow-hidden rounded-2xl border p-6 ${priority.card}`}><div className="mb-4 flex items-start justify-between"><div className={`rounded-xl border p-3 ${priority.panel}`}><Trophy className="h-5 w-5" /></div><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button onClick={onEdit} className="p-2 opacity-70 hover:opacity-100"><Edit2 className="h-4 w-4" /></button><button onClick={onDelete} className="p-2 opacity-70 hover:opacity-100"><Trash2 className="h-4 w-4" /></button></div></div><h3 className="truncate text-lg font-bold">{hackathon.name}</h3><div className={`mb-5 mt-1 flex flex-wrap items-center gap-2 ${priority.muted}`}><span className="text-xs">{hackathon.platform || 'Unspecified Platform'}</span><span className={`rounded border px-2 py-1 text-[10px] font-black uppercase ${priority.panel}`}>{hackathon.type === 'in-person' ? 'In Person' : 'Virtual'}</span><span className={`rounded border px-2 py-1 text-[10px] font-black uppercase ${priority.panel}`}>{priority.label}</span></div><div className="mb-6 space-y-3"><div className="flex items-center gap-2 text-sm"><Calendar className="h-4 w-4 opacity-65" />{new Date(hackathon.deadline).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</div><div className="flex items-center gap-2 text-sm font-bold"><Clock className="h-4 w-4" />{daysLeft < 0 ? 'Ended' : `${daysLeft} Days Left`}</div></div>{hackathon.link ? <a href={hackathon.link.startsWith('http') ? hackathon.link : `https://${hackathon.link}`} target="_blank" rel="noreferrer" className={`flex w-full items-center justify-center gap-2 rounded-lg border py-2 text-sm font-bold ${priority.panel}`}><ExternalLink className="h-4 w-4" />View Details</a> : <div className={`flex w-full items-center justify-center gap-2 rounded-lg border py-2 text-sm font-bold ${priority.panel}`}><CheckCircle className="h-4 w-4" />Attending In Person</div>}</div> };
const TaskCard: React.FC<{ item: CalendarItem; onEdit: () => void; onDelete: () => void; onMoveToToday: () => void }> = ({ item, onEdit, onDelete, onMoveToToday }) => { const priority = priorityFor(item.color); const isOverdue = item.date < formatDateInput(new Date()) && !item.completed; return <div className={`group relative overflow-hidden rounded-2xl border p-6 ${priority.card}`}><div className="mb-4 flex items-start justify-between"><div className={`rounded-xl border p-3 ${priority.panel}`}><Calendar className="h-5 w-5" /></div><div className="flex gap-1"><button onClick={onEdit} className="p-2 opacity-70 hover:opacity-100" aria-label={`Edit ${item.title}`}><Edit2 className="h-4 w-4" /></button><button onClick={onDelete} className="p-2 opacity-70 hover:opacity-100" aria-label={`Delete ${item.title}`}><Trash2 className="h-4 w-4" /></button></div></div><p className="text-[10px] font-black uppercase tracking-[0.18em] opacity-65">Scheduled Task</p><h3 className="mt-1 truncate text-lg font-bold">{item.title}</h3><div className={`mt-4 flex items-center gap-2 text-sm ${priority.muted}`}><Calendar className="h-4 w-4" />{new Date(item.date).toLocaleDateString('en-IN', { dateStyle: 'medium' })}{item.time && <><Clock className="ml-2 h-4 w-4" />{item.time}</>}</div>{isOverdue && <button onClick={onMoveToToday} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 py-2 text-sm font-black text-white hover:bg-indigo-500"><RotateCcw className="h-4 w-4" />Move to today</button>}<div className={`mt-3 flex w-full items-center justify-center gap-2 rounded-lg border py-2 text-sm font-bold ${priority.panel}`}><CheckCircle className="h-4 w-4" />{item.completed ? 'Completed' : priority.label}</div></div> };
const EmptyState: React.FC<{ filter: ContentFilter }> = ({ filter }) => <div className="col-span-full flex flex-col items-center rounded-3xl border-2 border-dashed border-slate-800 bg-slate-900/30 py-20 text-slate-500"><Trophy className="mb-4 h-12 w-12 opacity-20" /><p>No matching {filter === 'all' ? 'items' : filter} yet.</p></div>;
const Modal: React.FC<{ children: React.ReactNode }> = ({ children }) => <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-800 bg-slate-900 p-8 shadow-2xl">{children}</div></div>;
const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => <div><label className="mb-2 block text-xs font-bold uppercase tracking-widest text-slate-500">{label}</label><div className="[&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-slate-700 [&_input]:bg-slate-800 [&_input]:px-4 [&_input]:py-3 [&_input]:text-white [&_input]:outline-none [&_input]:focus:ring-2 [&_input]:focus:ring-amber-500">{children}</div></div>;
const Picker: React.FC<{ value: Priority; onChange: (value: Priority) => void }> = ({ value, onChange }) => <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{priorities.map((priority) => <button key={priority.value} onClick={() => onChange(priority.value)} className={`rounded-xl px-3 py-3 text-xs font-bold ${priority.picker} ${value === priority.value ? 'ring-2 ring-white ring-offset-2 ring-offset-slate-900' : 'opacity-70 hover:opacity-100'}`}>{priority.label}</button>)}</div>;
const Actions: React.FC<{ onCancel: () => void; onSave: () => void; label: string }> = ({ onCancel, onSave, label }) => <div className="mt-8 flex gap-4"><button onClick={onCancel} className="flex-1 rounded-xl bg-slate-800 py-3 font-bold text-slate-300 hover:bg-slate-700">Cancel</button><button onClick={onSave} className="flex-1 rounded-xl bg-amber-600 py-3 font-black text-white hover:bg-amber-500">{label}</button></div>;
const HackathonForm: React.FC<{ item: Omit<Hackathon, 'id'>; setItem: React.Dispatch<React.SetStateAction<Omit<Hackathon, 'id'>>>; linkType: 'submit' | 'in-person'; setLinkType: React.Dispatch<React.SetStateAction<'submit' | 'in-person'>>; editing: boolean; onCancel: () => void; onSave: () => void }> = ({ item, setItem, linkType, setLinkType, editing, onCancel, onSave }) => <><h3 className="mb-6 text-2xl font-black text-white">{editing ? 'Edit Hackathon' : 'Track New Hackathon'}</h3><div className="space-y-4"><Field label="Hackathon Name"><input autoFocus value={item.name} onChange={(e) => setItem({ ...item, name: e.target.value })} /></Field><Field label="Hackathon Type"><div className="grid grid-cols-2 gap-3">{(['in-person', 'virtual'] as const).map((type) => <button key={type} onClick={() => setItem({ ...item, type })} className={`rounded-xl px-4 py-3 text-sm font-bold ${item.type === type ? 'bg-amber-600 text-white' : 'bg-slate-800 text-slate-400'}`}>{type === 'in-person' ? 'In Person' : 'Virtual'}</button>)}</div></Field><Field label="Deadline Date"><input type="date" value={item.deadline} onChange={(e) => setItem({ ...item, deadline: e.target.value })} /></Field><Field label="Platform / Organizer"><input value={item.platform} onChange={(e) => setItem({ ...item, platform: e.target.value })} /></Field><Field label="Tag colour"><Picker value={item.priority || 'slate'} onChange={(priority) => setItem({ ...item, priority })} /></Field><Field label="Application Method"><div className="mb-3 grid grid-cols-2 gap-3"><button onClick={() => setLinkType('submit')} className={`rounded-xl px-4 py-3 text-sm font-bold ${linkType === 'submit' ? 'bg-sky-600 text-white' : 'bg-slate-800 text-slate-400'}`}>Submit Link</button><button onClick={() => { setLinkType('in-person'); setItem({ ...item, link: '' }); }} className={`rounded-xl px-4 py-3 text-sm font-bold ${linkType === 'in-person' ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-400'}`}>Attending In Person</button></div>{linkType === 'submit' ? <input value={item.link} onChange={(e) => setItem({ ...item, link: e.target.value })} /> : <div className="rounded-xl bg-emerald-900/20 px-4 py-3 text-center text-sm font-medium text-emerald-400">Will attend in person</div>}</Field></div><Actions onCancel={onCancel} onSave={onSave} label={editing ? 'Update Hackathon' : 'Start Tracking'} /></>;
const TaskForm: React.FC<{ task: { title: string; date: string; time: string; color: CalendarItem['color'] }; setTask: React.Dispatch<React.SetStateAction<{ title: string; date: string; time: string; color: CalendarItem['color'] }>>; editing: boolean; onCancel: () => void; onSave: () => void }> = ({ task, setTask, editing, onCancel, onSave }) => <><h3 className="text-2xl font-black text-white">{editing ? 'Edit Scheduled Task' : 'Add Scheduled Task'}</h3><p className="mt-1 text-sm text-slate-400">It will also appear in Solomon’s Order and Daily To-Do on its date.</p><div className="mt-6 space-y-4"><Field label="Task"><input autoFocus value={task.title} onChange={(e) => setTask({ ...task, title: e.target.value })} /></Field><Field label="Date"><input type="date" min="2026-01-01" max={getCalendarMaxDate()} value={task.date} onChange={(e) => setTask({ ...task, date: e.target.value })} /></Field><Field label="Time (optional)"><input type="time" value={task.time} onChange={(e) => setTask({ ...task, time: e.target.value })} /></Field><Field label="Tag colour"><Picker value={task.color} onChange={(color) => setTask({ ...task, color })} /></Field></div><Actions onCancel={onCancel} onSave={onSave} label={editing ? 'Save Changes' : 'Add to Calendar'} /></>;
export default HackathonTracker;
